/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_pinesw_ninedb_KvDbIterator */

#ifndef _Included_io_pinesw_ninedb_KvDbIterator
#define _Included_io_pinesw_ninedb_KvDbIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_pinesw_ninedb_KvDbIterator
 * Method:    itr_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pinesw_ninedb_KvDbIterator_itr_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_pinesw_ninedb_KvDbIterator
 * Method:    itr_next
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_pinesw_ninedb_KvDbIterator_itr_1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_pinesw_ninedb_KvDbIterator
 * Method:    itr_has_next
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_pinesw_ninedb_KvDbIterator_itr_1has_1next
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_pinesw_ninedb_KvDbIterator
 * Method:    itr_get_key
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pinesw_ninedb_KvDbIterator_itr_1get_1key
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_pinesw_ninedb_KvDbIterator
 * Method:    itr_get_value
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_pinesw_ninedb_KvDbIterator_itr_1get_1value
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
