/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_woutervh_ninedb_HrDatabase */

#ifndef _Included_io_woutervh_ninedb_HrDatabase
#define _Included_io_woutervh_ninedb_HrDatabase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_woutervh_ninedb_HrDatabase
 * Method:    open
 * Signature: (Ljava/lang/String;Lio/woutervh/ninedb/DbConfig;)J
 */
JNIEXPORT jlong JNICALL Java_io_woutervh_ninedb_HrDatabase_open
  (JNIEnv *, jclass, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
