/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_woutervh_ninedb_HrDatabase */

#ifndef _Included_io_woutervh_ninedb_HrDatabase
#define _Included_io_woutervh_ninedb_HrDatabase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_woutervh_ninedb_HrDatabase
 * Method:    db_open
 * Signature: (Ljava/lang/String;Lio/woutervh/ninedb/DbConfig;)J
 */
JNIEXPORT jlong JNICALL Java_io_woutervh_ninedb_HrDatabase_db_1open
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     io_woutervh_ninedb_HrDatabase
 * Method:    db_close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_woutervh_ninedb_HrDatabase_db_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_woutervh_ninedb_HrDatabase
 * Method:    kvdb_add
 * Signature: (J[B[B)V
 */
JNIEXPORT void JNICALL Java_io_woutervh_ninedb_HrDatabase_kvdb_1add
  (JNIEnv *, jclass, jlong, jbyteArray, jbyteArray);

/*
 * Class:     io_woutervh_ninedb_HrDatabase
 * Method:    kvdb_get
 * Signature: (J[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_io_woutervh_ninedb_HrDatabase_kvdb_1get
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     io_woutervh_ninedb_HrDatabase
 * Method:    kvdb_at
 * Signature: (JJ)Lio/woutervh/ninedb/KeyValuePair;
 */
JNIEXPORT jobject JNICALL Java_io_woutervh_ninedb_HrDatabase_kvdb_1at
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     io_woutervh_ninedb_HrDatabase
 * Method:    kvdb_flush
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_woutervh_ninedb_HrDatabase_kvdb_1flush
  (JNIEnv *, jclass, jlong);

/*
 * Class:     io_woutervh_ninedb_HrDatabase
 * Method:    kvdb_compact
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_woutervh_ninedb_HrDatabase_kvdb_1compact
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
