name: Build Node.js bindings for release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node:
          # - 18
          - 20

        architecture:
          - x64
          # - x86

        os:
          - ubuntu-20.04
          - windows-2022
          - macos-14

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          node-version: ${{ matrix.node }}
          architecture: ${{ matrix.architecture }}

      - name: Install Node.js dependencies
        run: npm install

      - name: Print info
        run: |
          echo "Node.js version: ${{ matrix.node }}"
          echo "Architecture: ${{ matrix.architecture }}"
          echo "Operating System: ${{ matrix.os }}"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - run: pip install -r requirements.txt

      - name: Print Conan version
        run: conan --version

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2.0
        with:
          cmake-version: "3.29.x"

      - name: Print CMake version
        run: cmake --version

      - name: Install conan dependencies
        run: conan install . -of build -pr:a profiles/profile_${{ matrix.os }}_${{ matrix.architecture }}_Release.conf

      # - name: Print debug info
      #   run: |
      #     echo "Conan path: ${{ github.workspace }}/build"
      #     echo "Node-API headers: ${{ github.workspace }}/node_modules/node-api-headers"
      #     echo "Toolchain file: ${{ github.workspace }}/build/conan_toolchain.cmake"
      #     ls -la ${{ github.workspace }}/build
      #     ls -la ${{ github.workspace }}/node_modules/node-api-headers
      #     ls -la ${{ github.workspace }}/build/conan_toolchain.cmake

      - name: Configure CMake
        shell: bash
        run: |
          cmake -B build \
            -S js \
            -DCMAKE_BUILD_TYPE=Release \
            -DCONAN_PATH="${{ github.workspace }}/build" \
            -DNODE_API_HEADERS="${{ github.workspace }}/node_modules/node-api-headers" \
            -DCMAKE_TOOLCHAIN_FILE="${{ github.workspace }}/build/conan_toolchain.cmake"

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: node -e '(require("./build/lib/ninedb"), console.log("Require OK!"))'

      # - name: Install packages
      #   run: npm install
      #   env:
      #     SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true

      # - name: Run tests
      #   run: npm test

      # - uses: actions/upload-artifact@v3
      #   if: github.repository_owner == 'sass' && github.event_name != 'pull_request'
      #   with:
      #     name: ${{ matrix.node }}-${{ matrix.architecture }}
      #     path: |
      #       vendor/**/binding.node
      #       build/Release/binding.pdb
